### PR TITLE
Improve algo

### LINKED ISSUE #31: Improve algorithm
**Is your feature request related to a problem? Please describe.**
Yes, it is a waste of bandwidth and time revisiting the profiles list page (because of `.back()`) after browsing the recent activity of every user.

**Describe the solution you'd like**
Instead, initially all the users' profile links of 2 (or) whatever the max number of pages to traverse can be **cached** into an array in memory before-hand and the same can be used for traversing each. This will remove the unnecessary usage of `.back()`. Rather, we can traverse through the array and basically visit one profile after other.

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by rajkumaar23**
## Description

Fixes #31 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots of the change
image

### CODE REVIEW

**Comment by rajkumaar23** [comment]
@ayushjainrksh 
- This needs to be rebased once we figure out the solution for the selector issue.
- While working on this, another thing that came to my notice was that : Does the program really read timings of 5 posts on each user's profile ? Because Linkedin renders some stuff only when you scroll down which is why I had to scroll down manually on the profile lists to even get the **Next** button to be on DOM.

**Comment by ayushjainrksh** [comment]
@rajkumaar23 Thanks for the PR! 

- It was supposed to read 5 posts. As far as I remember, there used to be pagination on the activity page but now I see a different design. I think we don't need to read any post other than the latest post to get if the user is active. So it makes sense to **change the logic to read only the latest activity** in a separate PR. But for now, it works fine, because `querySelectorAll` reads all available nodes(3-4) and parses each.

- You had to scroll down to get the Next button? Seems like LinkedIn's getting better at preventing scraping. Puppeteer has its ways though ;)

**Comment by rajkumaar23** [comment]
@ayushjainrksh This one's ready! :)

**Comment by ayushjainrksh** [comment]
@rajkumaar23 Thanks for this much-needed PR. That's a large changelog. I'm gonna go through this by tomorrow. Thanks for waiting.

**Comment by rajkumaar23** [comment]
It looks large because I moved that piece of code, outside of a 10+ line block 😆

**Review by ayushjainrksh — APPROVED** [review]

**Comment by ayushjainrksh** [comment]
@rajkumaar23 Thanks again for this PR.

**Pull request merged**
